const _PORT_ADDRESS = 7400;
const _NOTIFY_SERVER_URL = 'NOTIFY_SERVER'
const _NOTIFY_SERVER_WITHDRAW_URL = 'NOTIFY_SERVER'

module.exports = { _PORT_ADDRESS, _NOTIFY_SERVER_URL, _NOTIFY_SERVER_WITHDRAW_URL }